### PR TITLE
Development

### PR DESCRIPTION
**Pull request by i4seeu**

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
Hi @i4seeu, 

Good attempt on the Newsweek project. There are few things you need to fix though.

- You should get a better font for your logo. A font closer to the one used on the real site and ensure it carries enough weight almost as the one used in the main site. 
- You nav links should have the hover effect, give each link enough paddings and centralize the nav.
- The "In the magazine" container does not align with the preceding containers like it should. Please fix this. 
-  All the sections from the "Editor's pick" downward as well does not look well positioned. It seems there is more margin on the right than there is on the left. Please fix this as well and make all containers from top to bottom of the page align with each other. 
- The "© 2019 Newsweek" looks too big as well. Please try to clone the Newsweek site as best as possible. 

When you're done with those, you should request for another review and me as the TSE so I can follow up on it. 

Happy coding! :sunglasses:

**Comment by i4seeu** [comment]
Thanks for the comments, i will look into it but
hey did you check the site before you comment, because the in magazine you are talking about is like that in the magazine like its not aligned with the other.. could you please check the site and come back to me asap

**Comment by JamesOkunlade** [comment]
[image: Screenshot 2019-04-18 at 7.46.05 AM.png]

Here is an image that shows the show sections align. And so are the
preceding sections.

**Comment by i4seeu** [comment]
can't view the image

**Comment by i4seeu** [comment]
Screenshot from 2019-04-18 09-24-20

**Comment by i4seeu** [comment]
Any way i will try to put them in alignment

**Comment by JamesOkunlade** [comment]
The alignment I'm talking about is on the sides. The width of the Editors
pick look shorter than in the magazine. Please look closely and am sure
you'll see what my point is.

**Comment by i4seeu** [comment]
Oh, i see now.. you could have specified lol.. Thanks bra

**Comment by JamesOkunlade** [comment]
Lol.. I tried to.

Request for another review when you're done.

**Review by JamesOkunlade — APPROVED** [review]
### Great work @i4seeu 

This looks good now. Please merge to master, close pull request and fill the project completion form.

Good luck with your future project.

**Pull request merged**
